spring:
  datasource:
    platform: MYSQL
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/demo?serverTimezone=GMT%2B8
    username: root
    password: 123456
    schema: classpath:db/schema-mysql.sql
    data: classpath:db/data-mysql.sql
logging:
  level:
    root: debug


mybatis-plus:
  mapper-locations: com/example/demo/mapper/xml/*.xml
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.example.demo.entity
